name: spring_coffee
description: "ITP107 Finals Lab 1 - Spring Coffee (Login, Sign Up, Home) with named routes and Navigator methods."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_logo.png
    - assets/images/signup_logo.png
    - assets/images/menu.png
